### ISSUE TITLE
Tab Schedule: Сreating an event

### ISSUE THREAD

**Issue by margaritamikulionok** [panteleevb/Training-team-3#52]
Main Flow:
1.user comes to the page, chooses the day and clicks on the field of the day.
2.the form appears
example
![image](https://user-images.githubusercontent.com/33221440/37351391-0031d77c-26ec-11e8-897b-6e01f291aad0.png)
3.user fills in the name, time and participants
4.user click on button 'save'
5.created event become shown in the page

**Comment by drobch** [comment]
does the form use native google styles? Also can we use Fullcalendar?
