### ISSUE TITLE
Candidate's Review: Create page

### ISSUE THREAD

**Issue by margaritamikulionok** [panteleevb/Training-team-3#55]
Task Description
1. Create Page
2. Add button 'rewiev' in candidate's profile
3. Clicking on 'review' button opens the review popup
4. clicking 'save' will close the popup and update the page with new review

The review must be retained in the candidate's profile
![image](https://user-images.githubusercontent.com/33221440/37351758-d62728aa-26ec-11e8-9d9e-5395c182c058.png)

**Comment by ArtyomDyomkin** [comment]
What are these 4 forms for? Above them there is review text, right? So, what are they for?
